language: node_js
node_js:
- '12'
script: npm run lint && npm test
before_deploy: npm run build && cd dist
deploy:
  provider: npm
  email: leewayzhang@outlook.com
  skip_cleanup: true
  api_key:
    secure: mZGrZM7iNqs/v3A0G7U0YzngBGlLCNkn9s597wLKC7ciDqne9M8+XWuXduRETruOCTDHs3K7+iYK0pz4qepdO+qZFsSZqrZ1pGzZtdxqBqd5CbmEbtLJxeVc1/PJNoKSoGHKzdhmkz8MEeKTaOjXBr/An/ur1i1aNKmdixzFK2il5Jvpi3mdknYPiuSdzk2OfsdU7aXn/E681SjF8ZvAlUJJJt6ymYd3O1nvgqdNvX+BitvX3BFtFjFo4OZm1BCcV6f5GVj5jx9U5Ym4oxMfYjjC2KjEXzWLmOtU0IiumZ40unZP1rvmczZ53yOh76nn84iQESUviIeafLauqtHmkvzuj10+n2Abyo1YoS8ZHxGdxuc/3zFP05qK7lvwMezazqu1KQ6oe8WdcvC/02AfmXlhmRGiroDnRK1Xmc0wSyy4lc0mHfYEDITjEQ2qqsbvIniYJSyyZa0sHv/DoINpR4+xGnQQQu7HZeCIzFQ+vPXMnYVvkrZUW/5ML2cbosnzCUmD5cwx1/faM7ja/Naase8wtm4uuc25bcluc1aACHScKPxnoLhcjaMwrmN75RsvQmEfXZjMMnHAqip8coF1XzTbQUvvbwGjfO0f3rxsae4v3wU2MK129rfl/PgiM6EV3G06xXazeok03YZ9rZj8cLMtrmXydsRQKr0jPWYn3tM=
  on:
    tags: true
    branch: master
  tag: latest
